### PR TITLE
Added custom tag support

### PR DESCRIPTION
**Pull request by fledermaus101**
If merged change description to have the new environment variable.

### CODE REVIEW

**Comment by avivace** [comment]
Not sure how is this useful and how are we supposed to document what you added

**Comment by fledermaus101** [comment]
> Not sure how is this useful and how are we supposed to document what you added

Well in Risk of Rain 2 you can see tags on the right. With this command you can change them.
Also what I meant with changing the description was is to change the readme so the users now that this option exists.

**Comment by fledermaus101** [comment]
Sorry pressed wrong button.

**Comment by fledermaus101** [comment]
I'm new to Github say if I'm doing something wrong

**Comment by fledermaus101** [comment]
I edited the readme by myself. Now you could just merge. If you like this change.

**Comment by avivace** [comment]
Okay, now it makes sense for me. A part from accidentally closing this Pull Requesting and then reopening it, you did everything great!

The README change looks good to me so I'm gonna merge what you did. Thanks @fledermaus101 !

**Comment by fledermaus101** [comment]
Thanks!
Those comments mean much for me.

**Pull request merged**
